### PR TITLE
PreventDefaultAxis

### PR DESCRIPTION
**Pull request by dmitrif**
Added property determining on which axis you want to prevent default
actions. For example if set to restrict the y axis, scrolling will only
work as long as the flick is vertical. If the flick is recognized as a
horizontal movement the scrolling will be blocked.

The reason for this addition is when this is used for big components on web pages, a lot of times it will leave very miniscule amounts of area where a user can still scroll. This waits for the minimum treshold for recognizing a flick to be reached and then blocks one of the scrolling axis. Meaning if you do a mostly vertical touch movement, you can still scroll!

I tried to keep with your code guidelines and not change anything that wasn't required.

Thanks!

### CODE REVIEW

**Comment by originell** [comment]
+1 - this should really get merged!

**Comment by dmitrif** [comment]
I am guessing this project is dead?

**Comment by originell** [comment]
looks like it :-1:

**Comment by justspamjustin** [comment]
+1 Please merge!

**Comment by untitaker** [comment]
If i understand this correctly, Flickable.js currently blocks scrolling in any direction and this PR enables me to use vertical scrolling with horizontal flicking?

**Comment by dmitrif** [comment]
Yes. This PR allows you to restrict the flickable plugin to only listen on one axis and otherwise allow other events to be triggered (such as the browser scrolling).

**Pull request merged**
